### ISSUE TITLE
Codemeta error in JS project

### ISSUE THREAD

**Issue by mustafasoylu** [Materials-Data-Science-and-Informatics/somesy#22]
I tried to use somesy in a JS project without using package.json file. 

I created the `.somesy.toml` file as below.

```toml
[project]
name = "somesy"
version = "0.1.0"
description = "UI for PIDA project."
authors = [
    {family-names = "Soylu", given-names= "Mustafa", email = "m.soylu@fz-juelich.de", orcid = "https://orcid.org/0000-0003-2637-0432", contribution = "The main author, maintainer and tester.", contribution_begin = "2023-03-01", contribution_type = "code"},
]
maintainers = [
    {family-names = "Soylu", given-names= "Mustafa", email = "m.soylu@fz-juelich.de", orcid = "https://orcid.org/0000-0003-2637-0432", contribution = "The main author, maintainer and tester.", contribution_begin = "2023-03-01", contribution_type = "code"}
]
contributors = [
    {family-names = "Soylu", given-names= "Mustafa", email = "m.soylu@fz-juelich.de", orcid = "https://orcid.org/0000-0003-2637-0432", contribution = "The main author, maintainer and tester.", contribution_begin = "2023-03-01", contribution_type = "code"}
]
keywords = ["purls", "fair", "pida"]
license = "MIT"
repository = "https://jugit.fz-juelich.de/m.soylu/pida-ui.git"
homepage = "https://jugit.fz-juelich.de/m.soylu/pida-ui/-/tree/main"

[config.cli]
no_sync_cff = false
cff_file = "CITATION.cff"
no_sync_pyproject = true
no_sync_codemeta = false
codemeta_file = "codemeta.json"
show_info = false
verbose = false
debug = true
```

also, I used somesy as pre-commit hook with the below configuration.
```yaml
repos:
  # Metadata
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: '44e8fc9'
    hooks:
      - id: validate-cff
  - repo: https://github.com/fsfe/reuse-tool
    rev: 'v1.1.2'
    hooks:
      - id: reuse
  - repo: https://github.com/Materials-Data-Science-and-Informatics/somesy
    rev: 'bf34420'
    hooks:
      - id: somesy
 ```

I got the error below. I believe it is happening because [here](https://github.com/Materials-Data-Science-and-Informatics/somesy/blob/bf3442084feea80fefbc4129e69be99efc2a7957/src/somesy/codemeta/__init__.py#L23) `cm_sources` has pyproject file in default. 
```bash
somesy...................................................................Failed
- hook id: somesy
- exit code: 1

SomesyLogLevel.SILENT
DEBUG    Combined config (Defaults + File + CLI):                    sync.py:143
         SomesyConfig(                                                          
             input_file=PosixPath('.somesy.toml'),                              
             no_sync_cff=False,                                                 
             cff_file=PosixPath('CITATION.cff'),                                
             no_sync_pyproject=True,                                            
             pyproject_file=PosixPath('pyproject.toml'),                        
             no_sync_codemeta=False,                                            
             codemeta_file=PosixPath('codemeta.json'),                          
             show_info=False,                                                   
             verbose=False,                                                     
             debug=True                                                         
         )                                                                      
INFO     Syncing project metadata...                                 sync.py:146
INFO     Files to sync:                                              sync.py:147
INFO       - CITATION.cff:       CITATION.cff                        sync.py:153
INFO       - codemeta.json:      codemeta.json                       sync.py:157
                                                                                
DEBUG    Project metadata: {                                          sync.py:32
             'name': 'somesy',                                                  
             'description': 'UI for PIDA project.',                             
             'version': '0.1.0',                                                
             'authors': [                                                       
                 {                                                              
                     'email': 'm.soylu@fz-juelich.de',                          
                     'family_names': 'Soylu',                                   
                     'given_names': 'Mustafa',                                  
                     'orcid':                                                   
         AnyUrl('https://orcid.org/0000-0003-2637-0432',                        
         scheme='https', host='orcid.org', tld='org',                           
         host_type='domain', path='/0000-0003-2637-0432'),                      
                     'contribution': 'The main author, maintainer and           
         tester.',                                                              
                     'contribution_type': <ContributionTypeEnum.code:           
         'code'>,                                                               
                     'contribution_begin': datetime.date(2023, 3, 1)            
                 }                                                              
             ],                                                                 
             'maintainers': [                                                   
                 {                                                              
                     'email': 'm.soylu@fz-juelich.de',                          
                     'family_names': 'Soylu',                                   
                     'given_names': 'Mustafa',                                  
                     'orcid':                                                   
         AnyUrl('https://orcid.org/0000-0003-2637-0432',                        
         scheme='https', host='orcid.org', tld='org',                           
         host_type='domain', path='/0000-0003-2637-0432'),                      
                     'contribution': 'The main author, maintainer and           
         tester.',                                                              
                     'contribution_type': <ContributionTypeEnum.code:           
         'code'>,                                                               
                     'contribution_begin': datetime.date(2023, 3, 1)            
                 }                                                              
             ],                                                                 
             'contributors': [                                                  
                 {                                                              
                     'email': 'm.soylu@fz-juelich.de',                          
                     'family_names': 'Soylu',                                   
                     'given_names': 'Mustafa',                                  
                     'orcid':                                                   
         AnyUrl('https://orcid.org/0000-0003-2637-0432',                        
         scheme='https', host='orcid.org', tld='org',                           
         host_type='domain', path='/0000-0003-2637-0432'),                      
                     'contribution': 'The main author, maintainer and           
         tester.',                                                              
                     'contribution_type': <ContributionTypeEnum.code:           
         'code'>,                                                               
                     'contribution_begin': datetime.date(2023, 3, 1)            
                 }                                                              
             ],                                                                 
             'keywords': ['purls', 'fair', 'pida'],                             
             'license': <LicenseEnum.MIT: 'MIT'>,                               
             'repository':                                                      
         AnyUrl('https://jugit.fz-juelich.de/m.soylu/pida-ui.git',              
         scheme='https', host='jugit.fz-juelich.de', tld='de',                  
         host_type='domain', path='/m.soylu/pida-ui.git'),                      
             'homepage':                                                        
         AnyUrl('https://jugit.fz-juelich.de/m.soylu/pida-ui/-/tree/m           
         ain', scheme='https', host='jugit.fz-juelich.de', tld='de',            
         host_type='domain', path='/m.soylu/pida-ui/-/tree/main')               
         }                                                                      
VERBOSE  Loading CITATION.cff file.                                   sync.py:75
VERBOSE  Syncing CITATION.cff file.                                   sync.py:77
VERBOSE  Saved synced CITATION.cff file.                              sync.py:80
                                                                                
VERBOSE  Updating codemeta.json file.                             __init__.py:17
ERROR    Error: 'PathDistribution' object has no attribute 'name'    sync.py:173
DEBUG    Traceback (most recent call last):                          sync.py:174
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/somesy/cli/sync.py",             
         line 163, in sync                                                      
             sync_command(                                                      
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/somesy/commands/sync.            
         py", line 44, in sync                                                  
             update_codemeta(codemeta_file, cff_file)                           
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/somesy/codemeta/__ini            
         t__.py", line 32, in update_codemeta                                   
             cm_harvest = gen_codemeta(cm_sources)                              
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/somesy/codemeta/exec.            
         py", line 24, in gen_codemeta                                          
             g, res, args, _ = build(                                           
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/codemeta/codemeta.py"            
         , line 656, in build                                                   
             codemeta.parsers.python.parse_python(newgraph, res,                
         source, crosswalk, args)                                               
           File                                                                 
         "/local/home/m.soylu/.cache/pre-commit/repokjwy340c/py_env-            
         python3.9/lib/python3.9/site-packages/codemeta/parsers/pyth            
         on.py", line 223, in parse_python                                      
             packagename = pkg.name                                             
         AttributeError: 'PathDistribution' object has no attribute             
         'name'
```
