### ISSUE TITLE
Add organisation type for supplying contact information

### ISSUE THREAD

**Issue by flrnslbch** [Materials-Data-Science-and-Informatics/somesy#79]
We would like to add a general email as maintainer contact, for example:

pyproject.toml:
```yaml
[[project.maintainers]]
name = "Institute of Interesting Research"
email = "support@institue-interesting-research.edu"
```

codemeta.json:
```json
"maintainer": [
  {
    "@type": "Organisation",
    "name": "Institute of Interesting Research",
    "emai": "support@institue-interesting-research.edu",
    "@id": "https://orcid.org/xxxx-xxxx-xxxx-xxxx"
  },
````

citation.cff
```yaml
contact:
  - name: Institute of Interesting Research
  - email: support@institue-interesting-research.edu
```

Other projects such as NumPy also just have a general mail adress listed under maintainers/contact on PyPi.
CFF, codemeta and pyproject.toml all support this feature (the above examples should be valid).

Could you add this functionality to your datamodel and conversion tool?
